version: 2.1
parameters:
  run:
    default: true
    type: boolean

orbs:
  python: circleci/python@2.0.3
  flutter: circleci/flutter@2.0.2
jobs:
  test_python:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: cp config.sample.yml config.yml && MAPBOX_TOKEN=$MAPBOX_TOKEN python -m pytest
  test_flutter:
    executor: flutter/default
    parameters:
        app-dir:
            default: ./frontend
        cache-version:
            default: v1
    steps:
      - checkout
      - install_pub:
          app-dir: <<parameters.app-dir>>
          cache-version: <<parameters.cache-version>>
      - run:
          name: Run Flutter Tests
          command: cp .sample-env .env && flutter test
  deploy_prod:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Deploy
          command: ssh -oStrictHostKeyChecking=no root@tealtowns.org 'cd /var/www/tealtowns && git checkout . && git pull origin main && pip3 install -r ./requirements.txt && flutter upgrade && cd frontend && flutter build web && systemctl restart systemd_web_server_tealtowns.service'
workflows:
  test_app:
    when: << pipeline.parameters.run >>
    jobs:
      - test_python
      - test_flutter
  deploy_app:
    jobs:
      - test_python:
          filters:
            branches:
              only: main
      - test_flutter:
          filters:
            branches:
              only: main
      - deploy_prod:
          requires:
            - test_python
            - test_flutter
          filters:
            branches:
              only: main
