name: Deploy
on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  # TODO - python test fails when run this way - MAPBOX_TOKEN repository variable issue..
  # test:
  #   name: Test
  #   uses: teal-towns/tealtowns/.github/workflows/test.yml@main

  # Just do this so we can get cached pip dependencies on branches?
  cache-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    name: Deploy
    # needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Run SSH Command
        run: ssh -oStrictHostKeyChecking=no root@tealtowns.org 'cd /var/www/tealtowns && git checkout . && git pull origin main && pip3 install -r ./requirements.txt && flutter upgrade && cd frontend && flutter build web --web-renderer canvaskit && systemctl restart systemd_web_server_tealtowns.service'
